version: "3"
services:
    clean_data: 
        image: clean_image
        volumes:
            - "./data:/app/data"
    transform_data: 
        image: transform_image
        depends_on: 
            - clean_data
        volumes:
            - "./data:/app/data"
    train_model: 
        image: train_image
        depends_on: 
            - transform_data
            - clean_data
        volumes:
            - "./data:/app/data"
    prediction: 
        image: predict_image
        ports: 
            - "5000:5000"
        depends_on: 
            - train_model
            - transform_data
            - clean_data
        volumes:
            - "./data:/app/data" 